### ISSUE TITLE
bool value of Tensor with more than one value is ambiguous

### ISSUE THREAD

**Issue by TheCosmicStorm** [jason9693/MusicTransformer-pytorch#1]
When I'm trying to generate the new midi file I'm receiving this error:
RUNTIME ERROR: bool value of Tensor with more than one value is ambiguous. 
I decided to train the neural network with just 5 files before I sent it to my cluster. I was able to successfully generate the model and then I tried to generate some music with it. When I was running it through my debugger I successfully made it past line 47 ( result = mt(inputs, config.length, gen_summary_writer) ). I then print out the result and attempt to decode it. That is where it breaks. I have included the model if you see fit to test it yourself. I used the VScode debugger to see all the variables. 
Command Line: "python generate.py -c config/base.yml  config/generate.yml  config/train.yml -m model" (my default is Python 3 and I'm working in python 3.7)

[model.zip](https://github.com/jason9693/MusicTransformer-pytorch/files/3781293/model.zip)

**Comment by TheCosmicStorm** [comment]
Actually upon further testing I discovered some issues of my own
1. I hadn't properly generated a network
2. I realised you hadn't implemented line 52 correctly. It was missing the function generate.
However generate still has problems
1. I don't know what the decode function (decode_fn) is
2. pad token is missing

**Comment by jason9693** [comment]
Hi, @TheCosmicStorm 
Thank you for interested in this repo.

1. generate.py is not implemented yet.
2. Reason is same as 1
3. decode function has a role for token -> midi
4. pad token is not using in Music Transformer

 Thank you,

**Comment by jason9693** [comment]
Thank you for Issue :)
